### ISSUE TITLE
Add a reset.css file

### ISSUE THREAD

**Issue by huchthausen-julia** [huchthausen-julia/test_repo#1]
# Task: Add a reset.css file

We need to normalize some styling

- [ ] Remove all styles from existing files.
- [ ] Add the `src/reset.css` css styles to the application
  - [ ] Use one of the techniques you learned before

## Sample Solution
https://codesandbox.io/s/condescending-agnesi-chd28
