### ISSUE TITLE
Header & Booklist Component

### ISSUE THREAD

**Issue by huchthausen-julia** [huchthausen-julia/test_repo#2]
# Task: Header & Booklist Component

In this task we will practice the handling with single file components in Vue CLI projects.

## Solve the following tasks:

- [ ] Remove the HelloWorld component
- [ ] Remove dummy stuff from App.vue
- [ ] Add global css styles from `src/global.css`
  - [ ] Choose your favorite technique to add css
- [ ] Create a Header Component
  - [ ] Take use of provided resources `src/LayoutHeader`
  - [ ] Register it in the App.vue
- [ ] Create a BookList Component
  - [ ] Take use of provided resources `src/BookList`
  - [ ] Register it in the App.vue

## Sample Solution

https://codesandbox.io/s/blazing-silence-5suyo

**Comment by huchthausen-julia** [comment]
erl.
